### ISSUE TITLE
Unable To Connect to Stratis Node.

### ISSUE THREAD

**Issue by coati-time** [stratisproject/StraxUI#27]
Hello everyone.
I'm in trouble so please help me.

Ledger will no longer support STRAT tokens.
So, on November 26, 2020, I swapped START to STRAX, and received a STRAX token.
But now unable To Connect to Stratis Node from Wallet, No matter how many times I tried.
To avoid lost tokens, I want to move tokens from my STARX wallet to Binance account, is there a way?

  - I'm using macOS Catalina Version 10.15.7.
  - I tryed wallet version 1.0.0 and 1.2.0.
  - Previously it was connected to a node.
  - I have a CSV file generated by the following command during Token Swap.
    `sudo spctl --master-enable`
  - Last week, I connected to the node only twice in version 1.2.0, But I couldn't send token to Binance address.

Thank you in advance for your contributions and efforts.

**Comment by coati-time** [comment]
I found the link below and tried it.
https://www.reddit.com/r/stratisplatform/comments/llkboo/wallet_app_stuck_at_loading_screen/

`sudo ./STRAX\ Wallet.app/Contents/MacOS/STRAX\ Wallet `

It was the same log in versions 1.0.0 and 1.2.0.
There were two Fails.
This is the log.
```
[ '--enableSignalR' ]
Starting daemon /Users/coati/STRAX Wallet.app/Contents/resources/daemon/Stratis.StraxD
[ '-enableSignalR' ]
800
880
(node:5972) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
Stratis: info: Stratis.Bitcoin.FullNode[0]
      
      
           .d8888b. 88888888888 8888888b.         d8888 88888888888 8888888  .d8888b. 
          d88P  Y88b    888     888   Y88b       d88888     888       888   d88P  Y88b
          Y88b.         888     888    888      d88P888     888       888   Y88b.     
           "Y888b.      888     888   d88P     d88P 888     888       888    "Y888b.  
              "Y88b.    888     8888888P"     d88P  888     888       888       "Y88b.
                "888    888     888 T88b     d88P   888     888       888         "888
          Y88b  d88P    888     888  T88b   d8888888888     888       888   Y88b  d88P
           "Y8888P"     888     888   T88b d88P     888     888     8888888  "Y8888P" 
Stratis: 
      
      ················································································
      ················································································
      ······································STRAT·····································
      ···································STRATISSTRAT·································
      ·······························STRATISS····STRATIS······························
      ····························STRATIS···········STRATISS··························
      ·························STRATIS··················STRATIS·······················
      ·····················STRATISS························STRATISS···················
      ··················STRATIS································STRATIS················
      ···············STRATIS······································STRATIS·············
      ···········STRATIS··············································STRATIS·········
      ········STRATIS····················································STRATISS·····
      ····STRATISS···························································STRATIS··
      ··STRATIS································································STRAT··
      ··STRATISST··························································STRATISS···
      ··STRA··STRATIS···················································STRATIS·······
      ··STRA·····STRATISS············································STRATIS··········
      ··STRA·········STRATIS·····································STRATIS··············
      ··STRATI··········STRATISS······························STRATIS··········STRAT··
      ····STRATIS···········STRATIS·······················STRATIS··········STRATISST··
      ·······STRATISS··········STRATISS················STRATIS·········STRATISS··STR··
      ···········STRATIS···········STRATIS·········STRATIST·········STRATIST·····STR··
      ·····S········STRATIS···········STRATIS··STRATISS··········STRATIS········STRA··
      ····STRATIS·······STRATIS···········STRATISST··········STRATISS·········STRATI··
      ······STRATIS········STRATIS···········STR··········STRATIS·········STRATIS·····
      ·········STRATISS········STRATIS················STRATISS·········STRATIS········
      ·············STRATIS········STRATIS··········STRATIS·········STRATIS············
      ················STRATIS·········STRATIS··STRATISS·········STRATIS···············
      ···················STRATISS········STRATISSTR·········STRATISS··················
      ·······················STRATIS········STRA·········STRATIS······················
      ··························STRATISS·············STRATISS·························
      ······························STRATIS·······STRATIS·····························
      ·································STRATISSTRATISS································
      ·····································STRATIS····································
      ················································································
      
      
      

Stratis: info: Stratis.Bitcoin.FullNode[0]
      Full node initialized on StraxMain.

Stratis: 
Application starting, press Ctrl+C to cancel.


Stratis: info: Stratis.Bitcoin.FullNode[0]
      Starting node.

Stratis: info: Stratis.Bitcoin.Features.Api.ApiFeature[0]
      API starting on URL 'http://localhost:17103/'.

Stratis: info: Stratis.Bitcoin.Base.BaseFeature[0]
      Loading finalized block height.

Stratis: info: Stratis.Bitcoin.Base.BaseFeature[0]
      Loading chain.

Stratis: info: Stratis.Bitcoin.Base.BaseFeature[0]
      Chain loaded at height 203188.

Stratis: info: Stratis.Bitcoin.AsyncWork.AsyncProvider[0]
      FlushChain starting in 120 seconds.

Stratis: info: Stratis.Bitcoin.Base.BaseFeature[0]
      Loading peers from : /Users/coati/.stratisnode/strax/StraxMain.

Stratis: info: Stratis.Bitcoin.AsyncWork.AsyncProvider[0]
      Periodic peer flush starting in 300 seconds.

Stratis: fail: Stratis.Bitcoin.Builder.FullNodeFeatureExecutor[0]
      An error occurred: 'Stratis.Bitcoin.Consensus.ConsensusException: Violation of finality on height 203187 for RewindDataIndex.
         at Stratis.Bitcoin.Features.Consensus.ProvenBlockHeaders.RewindDataIndexCache.Initialize(Int32 tipHeight, ICoinView coinView) in /Users/runner/work/1/s/StratisFullNode/src/Stratis.Bitcoin.Features.Consensus/ProvenBlockHeaders/RewindDataIndexCache.cs:line 66
         at Stratis.Bitcoin.Features.Consensus.Rules.PosConsensusRuleEngine.Initialize(ChainedHeader chainTip) in /Users/runner/work/1/s/StratisFullNode/src/Stratis.Bitcoin.Features.Consensus/Rules/PosConsensusRuleEngine.cs:line 61
         at Stratis.Bitcoin.Base.BaseFeature.InitializeAsync() in /Users/runner/work/1/s/StratisFullNode/src/Stratis.Bitcoin/Base/BaseFeature.cs:line 235
         at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.<>c.<Initialize>b__3_1(IFullNodeFeature service) in /Users/runner/work/1/s/StratisFullNode/src/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 56
         at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean disposing) in /Users/runner/work/1/s/StratisFullNode/src/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 130'

Stratis: fail: Stratis.Bitcoin.Builder.FullNodeFeatureExecutor[0]
      An error occurred starting the application.

Stratis: There was a problem initializing the node. Details: 'System.AggregateException: One or more errors occurred. (Violation of finality on height 203187 for RewindDataIndex.)
 ---> Stratis.Bitcoin.Consensus.ConsensusException: Violation of finality on height 203187 for RewindDataIndex.
   at Stratis.Bitcoin.Features.Consensus.ProvenBlockHeaders.RewindDataIndexCache.Initialize(Int32 tipHeight, ICoinView coinView) in /Users/runner/work/1/s/StratisFullNode/src/Stratis.Bitcoin.Features.Consensus/ProvenBlockHeaders/RewindDataIndexCache.cs:line 66
   at Stratis.Bitcoin.Features.Consensus.Rules.PosConsensusRuleEngine.Initialize(ChainedHeader chainTip) in /Users/runner/work/1/s/StratisFullNode/src/Stratis.Bitcoin.Features.Consensus/Rules/PosConsensusRuleEngine.cs:line 61
   at Stratis.Bitcoin.Base.BaseFeature.InitializeAsync() in /Users/runner/work/1/s/StratisFullNode/src/Stratis.Bitcoin/Base/BaseFeature.cs:line 235
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.<>c.<Initialize>b__3_1(IFullNodeFeature service) in /Users/runner/work/1/s/StratisFullNode/src/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 56
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean disposing) in /Users/runner/work/1/s/StratisFullNode/src/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 130
   --- End of inner exception stack trace ---
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean disposing) in /Users/runner/work/1/s/StratisFullNode/src/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 148
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Initialize() in /Users/runner/work/1/s/StratisFullNode/src/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 53
   at Stratis.Bitcoin.FullNode.Start() in /Users/runner/work/1/s/StratisFullNode/src/Stratis.Bitcoin/FullNode.cs:line 219
   at Stratis.Bitcoin.Utilities.FullNodeExtensions.RunAsync(IFullNode node, CancellationToken cancellationToken) in /Users/runner/work/1/s/StratisFullNode/src/Stratis.Bitcoin/Utilities/FullNodeExtensions.cs:line 90
   at Stratis.Bitcoin.Utilities.FullNodeExtensions.RunAsync(IFullNode node) in /Users/runner/work/1/s/StratisFullNode/src/Stratis.Bitcoin/Utilities/FullNodeExtensions.cs:line 54
   at Stratis.StraxD.Program.Main(String[] args) in /Users/runner/work/1/s/StratisFullNode/src/Stratis.StraxD/Program.cs:line 80'

Stratis: Application is shutting down...

Stratis: The CancellationTokenSource has been disposed.
```

**Comment by dev0tion** [comment]
Hi,

This bug will be fixed in the upcoming wallet update.
For now please use the workaround:
Go to ~/.stratisnode/Strax/StraxMain and remove everything except the "wallets" folder.
